service: forfait-mobile

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  region: eu-west-3
  runtime: nodejs16.x
  disableRollback: true
  versionFunctions: false
  environment:
    PUSHED_APP_KEY: ${env:PUSHED_APP_KEY}
    PUSHED_APP_SECRET: ${env:PUSHED_APP_SECRET}

functions:
  checkOffers:
    handler: handler.checkOffers
    events:
      - schedule: rate(3 days)

