service: forfait-mobile

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  region: eu-west-3
  runtime: nodejs16.x
  disableRollback: true
  versionFunctions: false
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    TELEGRAM_CHAT_ID: ${env:TELEGRAM_CHAT_ID}

functions:
  checkOffers:
    handler: handler.checkOffers
    events:
      - schedule: rate(3 days)

